name: Zip and Upload to GCP Bucket

on:
  push:
    branches:
      - main  # Set to your default branch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Zip files
      run: zip -r archive.zip .

    - name: 'Google Auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: create json key
      run: echo ${{ secrets.GCP_SA_KEY }} > /tmp/temp_key.json

    - name: Set GCP Project ID
      run: gcloud auth activate-service-account --key-file  /tmp/temp_key.json

    - name: Upload to Google Cloud Storage
      run: gsutil cp archive.zip gs://cloud-functions-csye6225/
