name: Zip and Upload to GCP Bucket

on:
  push:
    branches:
      - main  # Set to your default branch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Zip files
      run: zip -r verify-email-function-source.zip .
    
    - id: 'deploy'
      uses: bitovi/github-actions-gcp-bucket@first-release
      with:
        gcp_access_key: ${{ secrets.GCP_SA_KEY }}
        bucket_name: cloud-functions
        file_name: verify-email-function-source.zip
